name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: Management Application Pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]'"
    timeout-minutes: 40
    env:
      NODE_VERSION: 16.14.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          version: '17'
      - name: Install Node Packages
        run: npm install
      - name: Create a new Release
        if: github.event_name == 'push' && github.ref='refs/heads/main'
        uses: actions/create-release@v2
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}

